# Generated by Django 2.2.5 on 2019-11-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190920_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
