# Generated by Django 2.2.5 on 2019-09-17 12:46

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190917_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 12, 46, 57, 328591), verbose_name='date published'),
        ),
    ]
