# Generated by Django 2.2.5 on 2019-09-17 14:35

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190917_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 14, 35, 39, 562247), verbose_name='date published'),
        ),
    ]
