# Generated by Django 2.2.5 on 2019-09-18 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190918_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 18, 15, 49, 13, 103566), verbose_name='date published'),
        ),
    ]
