# Generated by Django 2.2.5 on 2019-09-20 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190918_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 20, 16, 4, 6, 640414), verbose_name='date published'),
        ),
    ]
