# Generated by Django 2.2.5 on 2019-09-26 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190920_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 26, 15, 22, 11, 1364), verbose_name='date published'),
        ),
    ]
