# Generated by Django 2.2.5 on 2019-09-29 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190926_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 18, 30, 15, 18172), verbose_name='date published'),
        ),
    ]
