# Generated by Django 2.2.5 on 2019-11-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20191117_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['date_posted'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
    ]
